const buildKeywordExtractionPrompt = (questionText, hintText) => ({
  system: [
    "You extract genuinely technical, subject-specific vocabulary from a NEET (Indian medical entrance exam) exam question, for a tap-to-learn dictionary feature students use while practicing.",
    'Return ONLY a JSON object — no markdown, no commentary — with one key "terms": an array of strings.',
    "Include ANY word/short phrase a NEET student could benefit from tapping to learn more about: scientific terms, named structures/organs/organelles, processes, named laws/principles/theorems, techniques, instruments, and technical vocabulary specific to Biology/Chemistry/Physics — even ones a strong student might already know. This feature is opt-in (a student only taps a term if they want to), so a missed important term is a worse outcome than an extra one the student already knows and simply ignores — when in doubt, include it.",
    'EXCLUDE: common everyday English words, question-boilerplate phrasing (e.g. "which of the following", "correct answer", "regarding", "consider the statements"), generic verbs, and words a student would already understand purely from everyday English, not subject knowledge. This includes solution-narration phrases from a worked-out hint — "simplifying", "hence", "therefore", "final answer" — these are connective tissue in how the solution is explained, never vocabulary themselves, no matter how prominently they appear (e.g. on their own line, or right before the answer).',
    "EXCLUDE, ALWAYS: mathematical formulas, equations, numbers, units, standalone symbols/variables, and any LaTeX/math markup or command names (e.g. dfrac, frac, theta, omega, or anything that looks like it came from a LaTeX expression rather than plain English prose). A formula fragment is never a valid term, even if it looks unfamiliar. This includes DIMENSIONAL FORMULAS in every form they can appear — bracket notation like [MLT⁻²] or [ML²T⁻²], spelled out (\"M L T to the power negative 2\"), or described in words (\"m superscript ... t superscript ...\"). None of those are ever a valid term. If a question is ABOUT dimensional analysis, the valid term to extract is the concept name itself (e.g. \"dimensional formula\", \"dimensional analysis\") or the physical quantity being analyzed (e.g. \"torque\") — never the formula notation.",
    "EXCLUDE, ALWAYS: a bare single letter or symbol on its own (e.g. \"m\", \"t\", \"l\", \"v\", \"a\"), even when it's a standard variable for a real quantity. Only extract the full word for the quantity (e.g. \"mass\", \"time\", \"velocity\") if the question is genuinely testing that concept — never the one-letter symbol by itself. This also covers a variable name spoken as a phrase — \"v squared\", \"u squared\", \"x prime\" — these are still just a formula variable with a mathematical operation named in words, not a vocabulary term, even though they read like a two-word phrase.",
    "EXCLUDE, ALWAYS: generic measurement/geometry nouns that appear in nearly every numeric physics question and need no subject-specific explanation — e.g. distance, length, time, area, volume, radius, direction, speed, second, minute, differentiate. Only include one of these if the question is specifically defining or testing that concept itself, not just using it as a variable in a calculation.",
    "Each term should be a single word or a short (2-3 word) technical phrase, in its base/singular form, lowercase.",
    "Return up to 12 terms, ordered from most to least essential to understanding the core concept being tested. If a question genuinely has more than 12 worthwhile terms, keep the 12 most essential ones — never drop a genuinely important term just to shorten the list further than that. If there are no genuinely technical terms, return an empty array.",
    "",
    "Examples of the level of thoroughness expected:",
    'Physics — Question: "A vernier caliper has a main scale reading of 4 cm and 6 divisions of the vernier scale coincide with the main scale, with least count 0.01 cm. Find the zero error if the zero of the vernier scale is ahead of the main scale zero." → {"terms": ["vernier caliper", "main scale reading", "vernier scale", "least count", "zero error", "coincide"]}',
    'Chemistry — Question: "Which of the following exhibits Schottky defect in its crystal lattice due to missing cations and anions in equal number?" → {"terms": ["schottky defect", "crystal lattice", "cation", "anion"]}',
    'Biology — Question: "The mitochondria is the site of oxidative phosphorylation, which generates ATP using the electron transport chain." → {"terms": ["mitochondria", "oxidative phosphorylation", "atp", "electron transport chain"]}',
    'Physics — Question: "The dimensional formula of torque is" Hint: "Torque (τ) = Force × distance. Dimensional formula for (τ) = [MLT⁻²][L] = [ML²T⁻²]" → {"terms": ["torque", "dimensional formula", "force"]} — note "distance" is excluded (generic geometry noun, not the concept being tested) and the bracket notation [MLT⁻²]/[ML²T⁻²] is excluded entirely (formula notation, never a term) even though it dominates the hint text.',
  ].join("\n"),
  prompt: `Question: ${questionText}\n\nHint/Explanation: ${hintText || "(none)"}`,
});

module.exports = { buildKeywordExtractionPrompt };
